<?php

namespace DoctrineProxies\__CG__\Domain\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Provider extends \Domain\Entities\Provider implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'id', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'name', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'address', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'businessName', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'phoneNumber', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'zipCode', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'observations', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'brands', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'products', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'orders'];
        }

        return ['__isInitialized__', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'id', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'name', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'address', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'businessName', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'phoneNumber', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'zipCode', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'observations', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'brands', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'products', '' . "\0" . 'Domain\\Entities\\Provider' . "\0" . 'orders'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Provider $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getOrders(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', []);

        return parent::getOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrders(array $orders): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrders', [$orders]);

        parent::setOrders($orders);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(string $address): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinessName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinessName', []);

        return parent::getBusinessName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBusinessName(string $businessName): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusinessName', [$businessName]);

        parent::setBusinessName($businessName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber(string $phoneNumber): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phoneNumber]);

        parent::setPhoneNumber($phoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', []);

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode(string $zipCode): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', [$zipCode]);

        parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservations(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservations', []);

        return parent::getObservations();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservations(string $observations): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservations', [$observations]);

        parent::setObservations($observations);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrands(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrands', []);

        return parent::getBrands();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrands(array $brands): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrands', [$brands]);

        parent::setBrands($brands);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', []);

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setProducts($products): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProducts', [$products]);

        parent::setProducts($products);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdress(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdress', []);

        return parent::getAdress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdress(string $adress): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdress', [$adress]);

        parent::setAdress($adress);
    }

}
